### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Lmarty0** [ANNarchy/ANNarchy#20]
Hello, When I try to install ANNachy both on my system or in a conda environment with Python 3.10.12, I have the same message error : 
` × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 10, in <module>
          from setuptools.command.build import build
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.`

This message appears both when installing with pip or directly with the source code. 
Thank you for your help, I hope that this description could help you.

**Comment by vitay** [comment]
Hello,

thanks for the report!  Which version of setuptools do you have? Here they seem to mention setuptools.command.build has been introduced in v62:

<https://github.com/pypa/wheel/issues/487>

 Perhaps try upgrading it? `pip install --upgrade setuptools` (or with conda)

Several bug report mention M1 pro, is it what you have?

<https://github.com/UKPLab/sentence-transformers/issues/1652>

**Comment by Lmarty0** [comment]
Thank you for your answer,

I use `setuptools-70.0.0` after the indicated upgrading but the error message is the same. 
I don't have a M1 pro, as I work on Linux with a Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz

**Comment by vitay** [comment]
I do not see any relevant information on internet... Could you paste the output of the following command after downloading the source code:

```
pip install -e . -v
```

**Comment by Lmarty0** [comment]
Finally the problem was solved with the following commands : 
`sudo apt autoremove
pip install -U pip setuptools
pip3 install ANNarchy`

Thank you for you help !

**Comment by vitay** [comment]
ah, perhaps the pip version was indeed too old. thanks! feel free to ask further questions when using ANNarchy!
