### ISSUE TITLE
ANN-to-SNN conversion and newer h5py versions

### ISSUE THREAD

**Issue by hdinkelbach** [ANNarchy/ANNarchy#9]
During the merge of the ANN-to-SNN conversion prototype (commit 910e405), we noticed that h5py 3.7 (probably all versions > 3.0) lead to an error like the following:

```
Traceback (most recent call last):
  File "demo_mnist_cnn.py", line 36, in <module>
    snn_converter.init_from_keras_model("model_Conv.h5")
  File "[...]/ANNarchy/extensions/ann_to_snn_conversion/ANNtoSNNConverter.py", line 107, in init_from_keras_model
    weight_matrices, layer_order, input_dim = self._extract_weight_matrices(model_as_h5py)
  File "[...]/ANNarchy/extensions/ann_to_snn_conversion/ANNtoSNNConverter.py", line 309, in _extract_weight_matrices
    model_config = model_config.decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by hdinkelbach** [comment]
Turned out that the get() method in newer h5py methods decodes the bytes sequence already. Added a simple try-except to support h5py 2.x and 3.x versions.
